<div class="banner">
    <a href="#"><img src="<?php echo $this->basePath('img/banner.jpg') ?>" align="banner" /></a>
</div>
<div class="content">
    <div class="lefter">
        <div class="title">
            <h2 class="cBlue fB">产品展示<b class="cGrey fn">Products</b></h2>
        </div>
        <ul class="list_l">
            <li>
                <span class="listimg">
                    <img src="<?php echo $this->basePath('img/tran.gif') ?>" class="blank" /><a href="#"><img src="<?php echo $this->basePath('img/prod1.gif') ?>" alt="产品1" /></a>
                </span>
                <span class="listtxt">网格布</span>
            </li>
            <li>
                <span class="listimg">
                    <img src="<?php echo $this->basePath('img/tran.gif') ?>" class="blank" /><a href="#"><img src="<?php echo $this->basePath('img/prod2.gif') ?>" alt="产品2" /></a>
                </span>
                <span class="listtxt">橡塑板</span>
            </li>
            <li>
                <span class="listimg">
                    <img src="<?php echo $this->basePath('img/tran.gif') ?>" class="blank" /><a href="#"><img src="<?php echo $this->basePath('img/prod3.jpg') ?>" alt="产品3" /></a>
                </span>
                <span class="listtxt">橡塑管</span>
            </li>
            <li>
                <span class="listimg">
                    <img src="<?php echo $this->basePath('img/tran.gif') ?>" class="blank" /><a href="#"><img src="<?php echo $this->basePath('img/prod4.jpg') ?>" alt="产品3" /></a>
                </span>
                <span class="listtxt">珍珠岩</span>
            </li>
            <li>
                <span class="listimg">
                    <img src="<?php echo $this->basePath('img/tran.gif') ?>" class="blank" /><a href="#"><img src="<?php echo $this->basePath('img/prod1.gif') ?>" alt="产品1" /></a>
                </span>
                <span class="listtxt">网格布</span>
            </li>
            <li>
                <span class="listimg">
                    <img src="<?php echo $this->basePath('img/tran.gif') ?>" class="blank" /><a href="#"><img src="<?php echo $this->basePath('img/prod2.gif') ?>" alt="产品2" /></a>
                </span>
                <span class="listtxt">橡塑板</span>
            </li>
            <li>
                <span class="listimg">
                    <img src="<?php echo $this->basePath('img/tran.gif') ?>" class="blank" /><a href="#"><img src="<?php echo $this->basePath('img/prod3.jpg') ?>" alt="产品3" /></a>
                </span>
                <span class="listtxt">橡塑管</span>
            </li>
            <li>
                <span class="listimg">
                    <img src="<?php echo $this->basePath('img/tran.gif') ?>" class="blank" /><a href="#"><img src="<?php echo $this->basePath('img/prod4.jpg') ?>" alt="产品3" /></a>
                </span>
                <span class="listtxt">珍珠岩</span>
            </li>
            <li>
                <span class="listimg">
                    <img src="<?php echo $this->basePath('img/tran.gif') ?>" class="blank" /><a href="#"><img src="<?php echo $this->basePath('img/prod1.gif') ?>" alt="产品1" /></a>
                </span>
                <span class="listtxt">网格布</span>
            </li>
            <li>
                <span class="listimg">
                    <img src="<?php echo $this->basePath('img/tran.gif') ?>" class="blank" /><a href="#"><img src="<?php echo $this->basePath('img/prod2.gif') ?>" alt="产品2" /></a>
                </span>
                <span class="listtxt">橡塑板</span>
            </li>
            <li>
                <span class="listimg">
                    <img src="<?php echo $this->basePath('img/tran.gif') ?>" class="blank" /><a href="#"><img src="<?php echo $this->basePath('img/prod3.jpg') ?>" alt="产品3" /></a>
                </span>
                <span class="listtxt">橡塑管</span>
            </li>
            <li>
                <span class="listimg">
                    <img src="<?php echo $this->basePath('img/tran.gif') ?>" class="blank" /><a href="#"><img src="<?php echo $this->basePath('img/prod4.jpg') ?>" alt="产品3" /></a>
                </span>
                <span class="listtxt">珍珠岩</span>
            </li>
        </ul>
        <div class="blank10"></div>
        <div class="pages"><a href="#" class="pre">上一页</a><a class="current">1</a><a href="#?page=2">2</a><a href="#?page=3">3</a><a href="#?page=2" class="next">下一页</a></div>
        <div class="blank6"></div>
    </div>
    <div class="righter">
        <div class="rightBox">
            <a href="#" class="btn_s">我要留言</a>
        </div>
        <div class="blank10"></div>
        <div class="rightBox">
            <h3>最新公告<b class="cGrey fn">News</b></h3>
            <ul class="list_r">
                <li><a href="#">祝贺公司网站正式上线</a></li>
                <li><a href="#">禁止保温材料现场调配 保证...</a></li>
                <li><a href="#">节能65%烧结页岩空心砖面世</a></li>
            </ul>
        </div>
        <div class="blank10"></div>
        <div class="rightBox">
            <h3>友情链接<b class="cGrey fn">Links</b></h3>
            <ul class="list_r">
                <li><a href="#">卓越网上购物</a></li>
                <li><a href="#">京东网上商城</a></li>
                <li><a href="#">携程旅行网</a></li>
            </ul>
        </div>
    </div>
    <div class="hackbox"></div>
    
    
</div>