<div class="banner">
    <a href="#"><img src="<?php echo $this->basePath('img/config/banner.jpg') ?>" align="banner" /></a>
</div>
<div class="content">
    <div class="lefter">
        <div class="title">
            <h2 class="cBlue fB">产品展示<b class="cGrey fn">Products</b></h2>
        </div>
        <ul class="list_l minl">
        <?php foreach($paginator as $val):?>
            <li>
                <span class="listimg">
                    <img src="<?php echo $this->basePath('img/tran.gif') ?>" class="blank" /><a href="<?php echo $this->url(null,['action'=>'info'],['query'=>['id'=>$val->product_id]])?>"><img src="<?php echo $this->basePath('img/product/PC/'.$val->product_PCimg) ?>" title="<?php echo $val->product_feature?>" /></a>
                </span>
                <span class="listtxt"><?php echo $val->product_name?></span>
            </li>
        <?php endforeach;?>
        </ul>
        <div class="blank10"></div>
        <?php echo  $this->PaginationControl($paginator,'all','layout/PageLayout'); ?>
        <?php 
             if(count($this->items)>1)
          {
          echo $this->paginationControl($this->items,'Sliding','partials/pagination-control.phtml');                
          }
        ?>

        <div class="blank6"></div>
    </div>
    <div class="righter">
        <div class="rightBox">
            <a href="#" class="btn_s">我要留言</a>
        </div>
        <div class="blank10"></div>
        <div class="rightBox">
            <h3>最新公告<b class="cGrey fn">News</b></h3>
            <ul class="list_r">
                <li><a href="#">祝贺公司网站正式上线</a></li>
                <li><a href="#">禁止保温材料现场调配 保证...</a></li>
                <li><a href="#">节能65%烧结页岩空心砖面世</a></li>
            </ul>
        </div>
        <div class="blank10"></div>
        <div class="rightBox">
            <h3>友情链接<b class="cGrey fn">Links</b></h3>
            <ul class="list_r">
                <li><a href="#">卓越网上购物</a></li>
                <li><a href="#">京东网上商城</a></li>
                <li><a href="#">携程旅行网</a></li>
            </ul>
        </div>
    </div>
    <div class="hackbox"></div>
    
</div>