<div class="banner">
    <a href="#"><img src="<?php echo $this->basePath('img/banner.jpg') ?>" align="banner" /></a>
</div>
<div class="content">
    <div class="lefter">
        <div class="title">
            <h2 class="cBlue fB">客户留言<b class="cGrey fn">Guestbook</b></h2>
        </div>
        <div class="intro" style="padding-top:16px">
            <label>呢称：</label><input name="" type="text" /><br />
            <label>内容：</label><textarea name="" cols="" rows="" style="width:545px;height:138px"></textarea>
            <input name="" type="button" value="提交" class="btn_input" />
        </div>
        
    </div>
    <div class="righter">
        <div class="rightBox">
            <a href="#" class="btn_s">我要留言</a>
        </div>
        <div class="blank10"></div>
        <div class="rightBox">
            <h3>最新公告<b class="cGrey fn">News</b></h3>
            <ul class="list_r">
                <li><a href="#">祝贺公司网站正式上线</a></li>
                <li><a href="#">禁止保温材料现场调配 保证...</a></li>
                <li><a href="#">节能65%烧结页岩空心砖面世</a></li>
            </ul>
        </div>
        <div class="blank10"></div>
        <div class="rightBox">
            <h3>友情链接<b class="cGrey fn">Links</b></h3>
            <ul class="list_r">
                <li><a href="#">卓越网上购物</a></li>
                <li><a href="#">京东网上商城</a></li>
                <li><a href="#">携程旅行网</a></li>
            </ul>
        </div>
    </div>
    <div class="hackbox"></div>
    
    
</div>