<div class="banner">
    <a href="#"><img src="<?php echo $this->basePath('img/banner.jpg') ?>" align="banner" /></a>
</div>
<div class="content">
    <div class="lefter">
        <div class="title">
            <h2 class="cBlue fB">行业知识<b class="cGrey fn">Knowledge</b></h2>
        </div>
        <ul class="list_r" style="padding-right:40px">
            <li><a href="#">快讯:蒋孝严宣布共同建议 吁优化两岸合作条件  </a><span class="time2">2009-07-04</span></li>
            <li><a href="#">力拓间谍们情报交易链条曝光 包女歌手收买内奸 </a><span class="time2">2009-07-04</span></li>
            <li><a href="#">中石油乌鲁木齐石化分公司一成品油罐发生爆炸  </a><span class="time2">2009-07-04</span></li>
            <li><a href="#">英国出现首例甲型H1N1流感死亡病例 </a><span class="time2">2009-07-04</span></li>
            <li><a href="#">广东省招办就高考录取数据错误向考生致歉   </a><span class="time2">2009-07-04</span></li>
            <li><a href="#">广西遭遇今年首个热带风暴 “性急酋长”来倒水 </a><span class="time2">2009-07-04</span></li>
            <li><a href="#">四川达州持续遭受特大暴雨袭击</a><span class="time2">2009-07-04</span></li>
            <li><a href="#">快讯:蒋孝严宣布共同建议 吁优化两岸合作条件  </a><span class="time2">2009-07-04</span></li>
            <li><a href="#">力拓间谍们情报交易链条曝光 包女歌手收买内奸 </a><span class="time2">2009-07-04</span></li>
            <li><a href="#">中石油乌鲁木齐石化分公司一成品油罐发生爆炸  </a><span class="time2">2009-07-04</span></li>
            <li><a href="#">英国出现首例甲型H1N1流感死亡病例 </a><span class="time2">2009-07-04</span></li>
            <li><a href="#">广东省招办就高考录取数据错误向考生致歉   </a><span class="time2">2009-07-04</span></li>
            <li><a href="#">广西遭遇今年首个热带风暴 “性急酋长”来倒水 </a><span class="time2">2009-07-04</span></li>
            <li><a href="#">四川达州持续遭受特大暴雨袭击</a><span class="time2">2009-07-04</span></li>
        </ul>
        <div class="blank10"></div>
        <div class="pages"><a href="#" class="pre">上一页</a><a class="current">1</a><a href="#?page=2">2</a><a href="#?page=3">3</a><a href="#?page=2" class="next">下一页</a></div>
    </div>
    <div class="righter">
        <div class="rightBox">
            <a href="#" class="btn_s">我要留言</a>
        </div>
        <div class="blank10"></div>
        <div class="rightBox">
            <h3>最新公告<b class="cGrey fn">News</b></h3>
            <ul class="list_r">
                <li><a href="#">祝贺公司网站正式上线</a></li>
                <li><a href="#">禁止保温材料现场调配 保证...</a></li>
                <li><a href="#">节能65%烧结页岩空心砖面世</a></li>
            </ul>
        </div>
        <div class="blank10"></div>
        <div class="rightBox">
            <h3>友情链接<b class="cGrey fn">Links</b></h3>
            <ul class="list_r">
                <li><a href="#">卓越网上购物</a></li>
                <li><a href="#">京东网上商城</a></li>
                <li><a href="#">携程旅行网</a></li>
            </ul>
        </div>
    </div>
    <div class="hackbox"></div>
    
    
</div>