
<div class="banner">
    <a href="#"><img src="<?php echo $this->basePath('img/config/banner.jpg') ?>" align="banner" /></a>
</div>
<div class="content">
    <div class="lefter">
        <div class="title">
        <?php foreach($artcat as $val):?>
            <h2  class="cBlue fB <?php echo $type==$val->artCat_id?'moren':''?>"> <a  class="clear_text_decoration " href="<?php echo $this->url(null,['action'=>'index','pag'=>'1','type'=>$val->artCat_id])?>">
            <?php echo $val->artcat_title?><b class="cGrey fn">Knowledge</b></a></h2>
        <?php endforeach;?>  
        </div>
        <ul class="list_r" style="padding-right:40px;min-height: 290px;">
            <?php foreach($paginator as $val):?>
                <li><a href="<?php echo $this->url(null,['action'=>'info'],['query'=>['id'=>$val->article_id]])?>"> <?php    echo $sub->substr($val->article_title,0,25);echo $sub->substr($val->article_title,25,26)?'...':'';?></a><span class="time2"><?php echo date("Y-m-d H:i:s",$val->article_addTime);?></span></li>
            <?php endforeach;?>
        </ul>
        <div class="blank10"></div>
        <?php echo  $paginator?$this->PaginationControl($paginator,'all','layout/PageLayout'):''; ?>
    </div>
    <div class="righter">
        <div class="rightBox">
            <a href="#" class="btn_s">我要留言</a>
        </div>
        <div class="blank10"></div>
        <div class="rightBox">
            <h3>最新公告<b class="cGrey fn">News</b></h3>
            <ul class="list_r">
                <li><a href="#">祝贺公司网站正式上线</a></li>
                <li><a href="#">禁止保温材料现场调配 保证...</a></li>
                <li><a href="#">节能65%烧结页岩空心砖面世</a></li>
            </ul>
        </div>
        <div class="blank10"></div>
        <div class="rightBox">
            <h3>友情链接<b class="cGrey fn">Links</b></h3>
            <ul class="list_r">
                <li><a href="#">卓越网上购物</a></li>
                <li><a href="#">京东网上商城</a></li>
                <li><a href="#">携程旅行网</a></li>
            </ul>
        </div>
    </div>
    <div class="hackbox"></div>
    
    
</div>