<div class="banner">
    <a href="#"><img src="<?php echo $this->basePath('img/config/banner.jpg') ?>" align="banner" /></a>
</div>
<div class="content">
    <div class="lefter">
        <div class="title">
            <h2 class="cBlue fB">产品详细<b class="cGrey fn">Products</b></h2>
        </div>
        <div class="alertbox">
            <a href="<?php echo $this->url(null,['action'=>'index'])?>" />返回文章列表</a>
            <div class="clear"></div>
            <h1 ><?php echo $result->article_title ;?></h1>
            <div class="alertcenter">
                <?php echo $result->article_content ;?>
            </div>
            <div class="alertbottom">
                作者：<?php echo $result->article_author ;?><br />
                <?php echo date("Y-m-d H:i:s",$result->article_addTime);?><br />

            </div>
        </div>
        <div class="blank10"></div>
            
        <div class="blank6"></div>
    </div>
    <div class="righter">
        <div class="rightBox">
            <a href="#" class="btn_s">我要留言</a>
        </div>
        <div class="blank10"></div>
        <div class="rightBox">
            <h3>最新公告<b class="cGrey fn">News</b></h3>
            <ul class="list_r">
                <li><a href="#">祝贺公司网站正式上线</a></li>
                <li><a href="#">禁止保温材料现场调配 保证...</a></li>
                <li><a href="#">节能65%烧结页岩空心砖面世</a></li>
            </ul>
        </div>
        <div class="blank10"></div>
        <div class="rightBox">
            <h3>友情链接<b class="cGrey fn">Links</b></h3>
            <ul class="list_r">
                <li><a href="#">卓越网上购物</a></li>
                <li><a href="#">京东网上商城</a></li>
                <li><a href="#">携程旅行网</a></li>
            </ul>
        </div>
    </div>
    <div class="hackbox"></div>
    
</div>