
<div class="pages">
		  <?php echo $this->totalItemCount;?>条数据，共<?php echo  count($this->pagesInRange) ?>页
            <?php if (isset($this->previous)): ?>
                <a href="<?php echo $this->url(null,['action'=>'index','pag'=>$this->previous]) ?>" class="pre">上一页</a>
            <?php endif; ?>
    
            <?php if(count($this->pagesInRange)>1)foreach ($this->pagesInRange as $page): ?>

                    <a class="<?php echo  $page == $this->current?'active':''; ?>"
                    href="<?php echo $this->url(null,['action'=>'index','pag'=>$page]) ?> "> 
                     <?php echo $page; ?></a>
            <?php endforeach;?>
			<?php if (isset($this->next)): ?>
                <a href="<?php echo $this->url(null,['action'=>'index','pag'=>$this->next]) ?>" class="next">下一页</a>
            <?php endif; ?>
            </div>